version: '3'

services:
    webserver:
        build:
            context: ./docker/webserver
            args:
                SSH_PRV_KEY: "${ID_RSA}"
        volumes:
            - ./:/var/www/html
            - ./docker/webserver/development/default:/etc/nginx/sites-enabled/default
        networks:
            - app_network
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nodejs:
        build:
            context: ./
            dockerfile: ./docker/nodejs/Dockerfile
        volumes:
            - ./:/var/www/bo4e
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

