<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Anfragekategorie: string
{
    case PROZESSDATENBERICHT = 'PROZESSDATENBERICHT';
    case GERAETEUEBERNAHME = 'GERAETEUEBERNAHME';
    case WEITERVERPFLICHTUNG_BETRIEB_MELO = 'WEITERVERPFLICHTUNG_BETRIEB_MELO';
    case AENDERUNG_MELO = 'AENDERUNG_MELO';
    case STAMMDATEN_MALO_ODER_MELO = 'STAMMDATEN_MALO_ODER_MELO';
    case BILANZIERTE_MENGE_MEHR_MINDER_MENGEN = 'BILANZIERTE_MENGE_MEHR_MINDER_MENGEN';
    case ALLOKATIONSLISTE_MEHR_MINDER_MENGEN = 'ALLOKATIONSLISTE_MEHR_MINDER_MENGEN';
    case ENERGIEMENGE_UND_LEISTUNGSMAXIMUM = 'ENERGIEMENGE_UND_LEISTUNGSMAXIMUM';
    case ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF = 'ABRECHNUNG_MESSSTELLENBETRIEB_MSB_AN_LF';
    case AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION = 'AENDERUNG_PROGNOSEGRUNDLAGE_GERAETEKONFIGURATION';
    case AENDERUNG_GERAETEKONFIGURATION = 'AENDERUNG_GERAETEKONFIGURATION';
    case REKLAMATION_VON_WERTEN = 'REKLAMATION_VON_WERTEN';
    case LASTGANG_MALO_TRANCHE = 'LASTGANG_MALO_TRANCHE';
    case SPERRUNG = 'SPERRUNG';
    case ENTSPERRUNG = 'ENTSPERRUNG';
    case REKLAMATION_ZAEHLZEITDEFINITION = 'REKLAMATION_ZAEHLZEITDEFINITION';
    case ZEITREIHEN_IM_RAHMEN_BILANZKREISABRECHNUNG = 'ZEITREIHEN_IM_RAHMEN_BILANZKREISABRECHNUNG';
    case GERAETEWECHSELABSICHT = 'GERAETEWECHSELABSICHT';
    case AENDERUNG_KONZESSIONSABGABE = 'AENDERUNG_KONZESSIONSABGABE';
    case AENDERUNG_ZAEHLZEITDEFINITION = 'AENDERUNG_ZAEHLZEITDEFINITION';
    case UEBERMITTLUNG_WERTE_AN_ESA = 'UEBERMITTLUNG_WERTE_AN_ESA';
    case AENDERUNG = 'AENDERUNG';
    case BILANZKREISZUORDNUNGSLISTE = 'BILANZKREISZUORDNUNGSLISTE';
    case CLEARINGLISTE = 'CLEARINGLISTE';
    case NORMIERTES_PROFIL_PROFILSCHAR = 'NORMIERTES_PROFIL_PROFILSCHAR';
    case REDISPATCH_EINZELZEITREIHE_AUSFALLARBEIT = 'REDISPATCH_EINZELZEITREIHE_AUSFALLARBEIT';
    case REKLAMATION_PROFIL_PROFILSCHAR = 'REKLAMATION_PROFIL_PROFILSCHAR';
    case STAMMDATEN_MALO = 'STAMMDATEN_MALO';
    case STAMMDATEN_MELO = 'STAMMDATEN_MELO';
    case STAMMDATEN_TRANCHE = 'STAMMDATEN_TRANCHE';
}
