<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum BDEWArtikelnummer: string
{
    case LEISTUNG = 'LEISTUNG';
    case LEISTUNG_PAUSCHAL = 'LEISTUNG_PAUSCHAL';
    case GRUNDPREIS = 'GRUNDPREIS';
    case REGELENERGIE_ARBEIT = 'REGELENERGIE_ARBEIT';
    case REGELENERGIE_LEISTUNG = 'REGELENERGIE_LEISTUNG';
    case NOTSTROMLIEFERUNG_ARBEIT = 'NOTSTROMLIEFERUNG_ARBEIT';
    case NOTSTROMLIEFERUNG_LEISTUNG = 'NOTSTROMLIEFERUNG_LEISTUNG';
    case RESERVENETZKAPAZITAET = 'RESERVENETZKAPAZITAET';
    case RESERVELEISTUNG = 'RESERVELEISTUNG';
    case ZUSAETZLICHE_ABLESUNG = 'ZUSAETZLICHE_ABLESUNG';
    case PRUEFGEBUEHREN_AUSSERPLANMAESSIG = 'PRUEFGEBUEHREN_AUSSERPLANMAESSIG';
    case WIRKARBEIT = 'WIRKARBEIT';
    case SINGULAER_GENUTZTE_BETRIEBSMITTEL = 'SINGULAER_GENUTZTE_BETRIEBSMITTEL';
    case ABGABE_KWKG = 'ABGABE_KWKG';
    case ABSCHLAG = 'ABSCHLAG';
    case KONZESSIONSABGABE = 'KONZESSIONSABGABE';
    case ENTGELT_FERNAUSLESUNG = 'ENTGELT_FERNAUSLESUNG';
    case UNTERMESSUNG = 'UNTERMESSUNG';
    case BLINDMEHRARBEIT = 'BLINDMEHRARBEIT';
    case ENTGELT_ABRECHNUNG = 'ENTGELT_ABRECHNUNG';
    case SPERRKOSTEN = 'SPERRKOSTEN';
    case ENTSPERRKOSTEN = 'ENTSPERRKOSTEN';
    case MAHNKOSTEN = 'MAHNKOSTEN';
    case MEHR_MINDERMENGEN = 'MEHR_MINDERMENGEN';
    case INKASSOKOSTEN = 'INKASSOKOSTEN';
    case BLINDMEHRLEISTUNG = 'BLINDMEHRLEISTUNG';
    case ENTGELT_MESSUNG_ABLESUNG = 'ENTGELT_MESSUNG_ABLESUNG';
    case ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK = 'ENTGELT_EINBAU_BETRIEB_WARTUNG_MESSTECHNIK';
    case AUSGLEICHSENERGIE = 'AUSGLEICHSENERGIE';
    case AUSGLEICHSENERGIE_UNTERDECKUNG = 'AUSGLEICHSENERGIE_UNTERDECKUNG';
    case ZAEHLEINRICHTUNG = 'ZAEHLEINRICHTUNG';
    case WANDLER_MENGENUMWERTER = 'WANDLER_MENGENUMWERTER';
    case KOMMUNIKATIONSEINRICHTUNG = 'KOMMUNIKATIONSEINRICHTUNG';
    case TECHNISCHE_STEUEREINRICHTUNG = 'TECHNISCHE_STEUEREINRICHTUNG';
    case PARAGRAF_19_STROM_NEV_UMLAGE = 'PARAGRAF_19_STROM_NEV_UMLAGE';
    case BEFESTIGUNGSEINRICHTUNG = 'BEFESTIGUNGSEINRICHTUNG';
    case OFFSHORE_HAFTUNGSUMLAGE = 'OFFSHORE_HAFTUNGSUMLAGE';
    case FIXE_ARBEITSENTGELTKOMPONENTE = 'FIXE_ARBEITSENTGELTKOMPONENTE';
    case FIXE_LEISTUNGSENTGELTKOMPONENTE = 'FIXE_LEISTUNGSENTGELTKOMPONENTE';
    case UMLAGE_ABSCHALTBARE_LASTEN = 'UMLAGE_ABSCHALTBARE_LASTEN';
    case MEHRMENGE = 'MEHRMENGE';
    case MINDERMENGE = 'MINDERMENGE';
    case ENERGIESTEUER = 'ENERGIESTEUER';
    case SMARTMETER_GATEWAY = 'SMARTMETER_GATEWAY';
    case STEUERBOX = 'STEUERBOX';
    case MSB_INKL_MESSUNG = 'MSB_INKL_MESSUNG';
    case ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_1_MSBG';
    case ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_2_MSBG';
    case ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_3_MSBG';
    case ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_4_MSBG';
    case ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_2_5_MSBG';
    case ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG = 'ZUSATZDIENSTLEISTUNG_PARAGRAPH_35_3_MSBG';
}
