<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum BerechnungsformelNotwendigkeit: string
{
    case BERECHNUNGSFORMEL_NOTWENDIG = 'BERECHNUNGSFORMEL_NOTWENDIG';
    case BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN = 'BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN';
    case BERECHNUNGSFORMEL_TRIVIAL = 'BERECHNUNGSFORMEL_TRIVIAL';
    case BERECHNUNGSFORMEL_NICHT_NOTWENDIG = 'BERECHNUNGSFORMEL_NICHT_NOTWENDIG';
}
