<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum BOTyp: string
{
    case ANSPRECHPARTNER = 'ANSPRECHPARTNER';
    case AVIS = 'AVIS';
    case ENERGIEMENGE = 'ENERGIEMENGE';
    case GESCHAEFTSOBJEKT = 'GESCHAEFTSOBJEKT';
    case GESCHAEFTSPARTNER = 'GESCHAEFTSPARTNER';
    case MARKTLOKATION = 'MARKTLOKATION';
    case MARKTTEILNEHMER = 'MARKTTEILNEHMER';
    case MESSLOKATION = 'MESSLOKATION';
    case ZAEHLER = 'ZAEHLER';
    case KOSTEN = 'KOSTEN';
    case TARIF = 'TARIF';
    case PREISBLATT = 'PREISBLATT';
    case PREISBLATTNETZNUTZUNG = 'PREISBLATTNETZNUTZUNG';
    case PREISBLATTMESSUNG = 'PREISBLATTMESSUNG';
    case PREISBLATTUMLAGEN = 'PREISBLATTUMLAGEN';
    case PREISBLATTDIENSTLEISTUNG = 'PREISBLATTDIENSTLEISTUNG';
    case PREISBLATTKONZESSIONSABGABE = 'PREISBLATTKONZESSIONSABGABE';
    case ZEITREIHE = 'ZEITREIHE';
    case LASTGANG = 'LASTGANG';
    case HANDELSUNSTIMMIGKEIT = 'HANDELSUNSTIMMIGKEIT';
    case ANFRAGE = 'ANFRAGE';
    case AUFTRAG = 'AUFTRAG';
    case STATUSMITTEILUNG = 'STATUSMITTEILUNG';
    case BERECHNUNGSFORMEL = 'BERECHNUNGSFORMEL';
    case RECHNUNG = 'RECHNUNG';
    case BILANZIERUNG = 'BILANZIERUNG';
    case NETZNUTZUNGSVERTRAG = 'NETZNUTZUNGSVERTRAG';
    case MESSSTELLENBETRIEBSVERTRAG = 'MESSSTELLENBETRIEBSVERTRAG';
    case ENERGIELIEFERVERTRAG = 'ENERGIELIEFERVERTRAG';
    case SPERRAUFTRAG = 'SPERRAUFTRAG';
    case ANGEBOT = 'ANGEBOT';
    case TRANCHE = 'TRANCHE';
}
