<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Gebiettyp: string
{
    case REGELZONE = 'REGELZONE';
    case MARKTGEBIET = 'MARKTGEBIET';
    case BILANZIERUNGSGEBIET = 'BILANZIERUNGSGEBIET';
    case VERTEILNETZ = 'VERTEILNETZ';
    case TRANSPORTNETZ = 'TRANSPORTNETZ';
    case REGIONALNETZ = 'REGIONALNETZ';
    case AREALNETZ = 'AREALNETZ';
    case GRUNDVERSORGUNGSGEBIET = 'GRUNDVERSORGUNGSGEBIET';
    case VERSORGUNGSGEBIET = 'VERSORGUNGSGEBIET';
}
