<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Geraetetyp: string
{
    case WECHSELSTROMZAEHLER = 'WECHSELSTROMZAEHLER';
    case DREHSTROMZAEHLER = 'DREHSTROMZAEHLER';
    case ZWEIRICHTUNGSZAEHLER = 'ZWEIRICHTUNGSZAEHLER';
    case RLM_ZAEHLER = 'RLM_ZAEHLER';
    case IMS_ZAEHLER = 'IMS_ZAEHLER';
    case BALGENGASZAEHLER = 'BALGENGASZAEHLER';
    case MAXIMUMZAEHLER = 'MAXIMUMZAEHLER';
    case MULTIPLEXANLAGE = 'MULTIPLEXANLAGE';
    case PAUSCHALANLAGE = 'PAUSCHALANLAGE';
    case VERSTAERKERANLAGE = 'VERSTAERKERANLAGE';
    case SUMMATIONSGERAET = 'SUMMATIONSGERAET';
    case IMPULSGEBER = 'IMPULSGEBER';
    case EDL_21_ZAEHLERAUFSATZ = 'EDL_21_ZAEHLERAUFSATZ';
    case VIER_QUADRANTEN_LASTGANGZAEHLER = 'VIER_QUADRANTEN_LASTGANGZAEHLER';
    case MENGENUMWERTER = 'MENGENUMWERTER';
    case STROMWANDLER = 'STROMWANDLER';
    case SPANNUNGSWANDLER = 'SPANNUNGSWANDLER';
    case DATENLOGGER = 'DATENLOGGER';
    case KOMMUNIKATIONSANSCHLUSS = 'KOMMUNIKATIONSANSCHLUSS';
    case MODEM = 'MODEM';
    case TELEKOMMUNIKATIONSEINRICHTUNG = 'TELEKOMMUNIKATIONSEINRICHTUNG';
    case KOMMUNIKATIONSEINRICHTUNG = 'KOMMUNIKATIONSEINRICHTUNG';
    case DREHKOLBENGASZAEHLER = 'DREHKOLBENGASZAEHLER';
    case TURBINENRADGASZAEHLER = 'TURBINENRADGASZAEHLER';
    case ULTRASCHALLZAEHLER = 'ULTRASCHALLZAEHLER';
    case WIRBELGASZAEHLER = 'WIRBELGASZAEHLER';
    case MODERNE_MESSEINRICHTUNG = 'MODERNE_MESSEINRICHTUNG';
    case ELEKTRONISCHER_HAUSHALTSZAEHLER = 'ELEKTRONISCHER_HAUSHALTSZAEHLER';
    case STEUEREINRICHTUNG = 'STEUEREINRICHTUNG';
    case TECHNISCHESTEUEREINRICHTUNG = 'TECHNISCHESTEUEREINRICHTUNG';
    case TARIFSCHALTGERAET = 'TARIFSCHALTGERAET';
    case RUNDSTEUEREMPFAENGER = 'RUNDSTEUEREMPFAENGER';
    case OPTIONALE_ZUS_ZAEHLEINRICHTUNG = 'OPTIONALE_ZUS_ZAEHLEINRICHTUNG';
    case MESSWANDLERSATZ_IMS_MME = 'MESSWANDLERSATZ_IMS_MME';
    case KOMBIMESSWANDLER_IMS_MME = 'KOMBIMESSWANDLER_IMS_MME';
    case TARIFSCHALTGERAET_IMS_MME = 'TARIFSCHALTGERAET_IMS_MME';
    case RUNDSTEUEREMPFAENGER_IMS_MME = 'RUNDSTEUEREMPFAENGER_IMS_MME';
    case TEMPERATUR_KOMPENSATION = 'TEMPERATUR_KOMPENSATION';
    case HOECHSTBELASTUNGS_ANZEIGER = 'HOECHSTBELASTUNGS_ANZEIGER';
    case SONSTIGES_GERAET = 'SONSTIGES_GERAET';
    case SMARTMETERGATEWAY = 'SMARTMETERGATEWAY';
    case STEUERBOX = 'STEUERBOX';
    case BLOCKSTROMWANDLER = 'BLOCKSTROMWANDLER';
    case KOMBIMESSWANDLER = 'KOMBIMESSWANDLER';
    case MODEM_GSM = 'MODEM_GSM';
    case ETHERNET_KOM = 'ETHERNET_KOM';
    case PLC_COM = 'PLC_COM';
    case MODEM_FESTNETZ = 'MODEM_FESTNETZ';
    case DSL_KOM = 'DSL_KOM';
    case LTE_KOM = 'LTE_KOM';
    case DICHTEMENGENUMWERTER = 'DICHTEMENGENUMWERTER';
    case TEMPERATURMENGENUMWERTER = 'TEMPERATURMENGENUMWERTER';
    case ZUSTANDSMENGENUMWERTER = 'ZUSTANDSMENGENUMWERTER';
    case MESSDATENREGISTRIERGERAET = 'MESSDATENREGISTRIERGERAET';
    case WANDLER = 'WANDLER';
}
