<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Handelsunstimmigkeitstyp: string
{
    case HANDELSRECHNUNG = 'HANDELSRECHNUNG';
    case LIEFERSCHEIN_HANDELSUNSTIMMIGKEITSTYP = 'LIEFERSCHEIN_HANDELSUNSTIMMIGKEITSTYP';
    case LIEFERSCHEIN_GRUND_ARBEITSPREIS = 'LIEFERSCHEIN_GRUND_ARBEITSPREIS';
    case LIEFERSCHEIN_ARBEITS_LEISTUNGSPREIS = 'LIEFERSCHEIN_ARBEITS_LEISTUNGSPREIS';
}
