<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Kalkulationsmethode: string
{
    case KEINE = 'KEINE';
    case STAFFELN = 'STAFFELN';
    case ZONEN = 'ZONEN';
    case VORZONEN_GP = 'VORZONEN_GP';
    case SIGMOID = 'SIGMOID';
    case BLINDARBEIT_GT_50_PROZENT = 'BLINDARBEIT_GT_50_PROZENT';
    case BLINDARBEIT_GT_40_PROZENT = 'BLINDARBEIT_GT_40_PROZENT';
    case AP_GP_ZONEN = 'AP_GP_ZONEN';
    case LP_INSTALL_LEISTUNG = 'LP_INSTALL_LEISTUNG';
    case AP_TRANSPORT_ODER_VERTEILNETZ = 'AP_TRANSPORT_ODER_VERTEILNETZ';
    case AP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNTZ_SIGMOID = 'AP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID';
    case LP_JAHRESVERBRAUCH = 'LP_JAHRESVERBRAUCH';
    case LP_TRANSPORT_ODER_VERTEILNETZ = 'LP_TRANSPORT_ODER_VERTEILNETZ';
    case LP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNTZ_SIGMOID = 'LP_TRANSPORT_ODER_VERTEILNETZ_ORTSVERTEILNETZ_SIGMOID';
    case FUNKTIONEN = 'FUNKTIONEN';
    case VERBR_UE_SLP_FKT_WEITERE_BER_LGK = 'VERBRAUCH_UEBER_SLP_GRENZE_FUNKTIONSBEZOGEN_WEITERE_BERECHNUNG_ALS_LGK';
}
