<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Kommunikationsrolle: string
{
    case DATENAUSTAUSCH = 'DATENAUSTAUSCH';
    case RAHMENVERTRAEGE = 'RAHMENVERTRAEGE';
    case KUENDIGUNGSPROZESSE = 'KUENDIGUNGSPROZESSE';
    case WECHSELPROZESSE = 'WECHSELPROZESSE';
    case STAMMDATENPROZESSE = 'STAMMDATENPROZESSE';
    case EINSPEISEPROZESSE = 'EINSPEISEPROZESSE';
    case ABRECHNUNGSPROZESSE = 'ABRECHNUNGSPROZESSE';
    case MMMA_PROZESSE = 'MMMA_PROZESSE';
    case BEWEGUNGSDATEN = 'BEWEGUNGSDATEN';
    case ENT_SPERR_PROZESSE = 'ENT_SPERR_PROZESSE';
    case BILANZIERUNGSPROZESSE = 'BILANZIERUNGSPROZESSE';
    case NETZANSCHLUSS_ANLAGEN = 'NETZANSCHLUSS_ANLAGEN';
}
