<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Profilart: string
{
    case ART_STANDARDLASTPROFIL = 'ART_STANDARDLASTPROFIL';
    case ART_TAGESPARAMETERABHAENGIGES_LASTPROFIL = 'ART_TAGESPARAMETERABHAENGIGES_LASTPROFIL';
    case ART_LASTPROFIL = 'ART_LASTPROFIL';
}
