<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum SonderrechnungsArt: string
{
    case KONZESSIONSABGABE_TESTAT = 'KONZESSIONSABGABE_TESTAT';
    case INDIVIDUELL_ATYPISCH = 'INDIVIDUELL_ATYPISCH';
    case INDIVIDUELL_SINGULAER = 'INDIVIDUELL_SINGULAER';
    case KWKG_UMLAGE = 'KWKG_UMLAGE';
    case OFFSHORE_UMLAGE = 'OFFSHORE_UMLAGE';
    case P19_STROM_NEV_UMLAGE = 'P19_STROM_NEV_UMLAGE';
    case P18_ABLAV = 'P18_ABLAV';
    case KONZESSIONSABGABE_WECHSEL_RLM = 'KONZESSIONSABGABE_WECHSEL_RLM';
}
