<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Statusanlass: string
{
    case KOMMUNIKATIONSSTOERUNG = 'KOMMUNIKATIONSSTOERUNG';
    case STATUS_GERAETEWECHSEL = 'STATUS_GERAETEWECHSEL';
    case MESSEINRICHTUNG_GESTOERT_DEFEKT = 'MESSEINRICHTUNG_GESTOERT_DEFEKT';
    case KEINE_STOERUNG_FESTSTELLBAR = 'KEINE_STOERUNG_FESTSTELLBAR';
    case STOERUNGSBEHEBUNG_NICHT_MOEGLICH = 'STOERUNGSBEHEBUNG_NICHT_MOEGLICH';
    case REPARATUR_OHNE_GERAETEWECHSEL = 'REPARATUR_OHNE_GERAETEWECHSEL';
}
