<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum StatusErzeugendeMarktlokation: string
{
    case EINSPEISEVERGUETUNG_PARAGRAPH_37 = 'EINSPEISEVERGUETUNG_PARAGRAPH_37';
    case GEFOERDERTE_DIREKTVERMARKTUNG = 'GEFOERDERTE_DIREKTVERMARKTUNG';
    case SONSTIGE_DIREKTVERMARKTUNG = 'SONSTIGE_DIREKTVERMARKTUNG';
    case VERMARKTUNG_OHNE_GESETZL_VERGUETUNG = 'VERMARKTUNG_OHNE_GESETZL_VERGUETUNG';
    case KWKG_VERGUETUNG = 'KWKG_VERGUETUNG';
    case EINSPEISEVERGUETUNG_PARAGRAPH_38_AUSFALLVERGUETUNG = 'EINSPEISEVERGUETUNG_PARAGRAPH_38_AUSFALLVERGUETUNG';
}
