<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum VerwendungszweckValue: string
{
    case NETZNUTZUNGSABRECHNUNG = 'NETZNUTZUNGSABRECHNUNG';
    case BILANZKREISABRECHNUNG = 'BILANZKREISABRECHNUNG';
    case MEHRMINDERMENGENABRECHNUNG = 'MEHRMINDERMENGENABRECHNUNG';
    case ENDKUNDENABRECHNUNG = 'ENDKUNDENABRECHNUNG';
    case UEBERMITTLUNG_AN_DAS_HKNR = 'UEBERMITTLUNG_AN_DAS_HKNR';
    case BLINDARBEITSABRECHNUNG = 'BLINDARBEITSABRECHNUNG';
    case ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS = 'ERMITTLUNG_AUSGEGLICHENHEIT_BILANZKREIS';
}
