<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum WahlrechtPrognosegrundlage: string
{
    case DURCH_LF = 'DURCH_LF';
    case DURCH_LF_NICHT_GEGEBEN = 'DURCH_LF_NICHT_GEGEBEN';
    case NICHT_WEGEN_GROSSEN_VERBRAUCHS = 'NICHT_WEGEN_GROSSEN_VERBRAUCHS';
    case NICHT_WEGEN_EIGENVERBRAUCH = 'NICHT_WEGEN_EIGENVERBRAUCH';
    case NICHT_WEGEN_TAGES_VERBRAUCH = 'NICHT_WEGEN_TAGES_VERBRAUCH';
    case NICHT_WEGEN_ENWG = 'NICHT_WEGEN_ENWG';
}
