<?php

declare(strict_types=1);

namespace Conuti\BO4E\v1\Enum;

enum Zaehlertyp: string
{
    case DREHSTROMZAEHLER = 'DREHSTROMZAEHLER';
    case BALGENGASZAEHLER = 'BALGENGASZAEHLER';
    case DREHKOLBENZAEHLER = 'DREHKOLBENZAEHLER';
    case SMARTMETER = 'SMARTMETER';
    case LEISTUNGSZAEHLER = 'LEISTUNGSZAEHLER';
    case MAXIMUMZAEHLER = 'MAXIMUMZAEHLER';
    case TURBINENRADGASZAEHLER = 'TURBINENRADGASZAEHLER';
    case ULTRASCHALLGASZAEHLER = 'ULTRASCHALLGASZAEHLER';
    case WECHSELSTROMZAEHLER = 'WECHSELSTROMZAEHLER';
    case WIRBELGASZAEHLER = 'WIRBELGASZAEHLER';
    case MESSDATENREGISTRIERGERAET = 'MESSDATENREGISTRIERGERAET';
    case ELEKTRONISCHERHAUSHALTSZAEHLER = 'ELEKTRONISCHERHAUSHALTSZAEHLER';
    case SONDERAUSSTATTUNG = 'SONDERAUSSTATTUNG';
    case WASSERZAEHLER = 'WASSERZAEHLER';
    case MODERNEMESSEINRICHTUNG = 'MODERNEMESSEINRICHTUNG';
}
